import {
  whiteA,
  slateA,
  mauveA,
  grayA,
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  cyan,
  teal,
  green,
  grass,
  brown,
  orange,
  sky,
  mint,
  lime,
  yellow,
  amber,
  gold,
  bronze,
} from "@radix-ui/colors";

// Spread the scales in your light and dark themes
import { createStitches } from "@stitches/react";

const { styled } = createStitches({
  media: {
    md: "(min-width: 40rem)",
    lg: "(min-width: 1024px)",
  },
  theme: {
    fonts: {
      ui: "Source Sans Pro, sans-serif",
      branding: "Shippori Mincho B1, serif",
      sans: "Libre Franklin, sans-serif",
      serif: "Source Serif 4, serif",
    },
    fontSizes: {
      6: "4.209rem",
      5: "3.157rem",
      4: "2.369rem",
      3: "1.777rem",
      2: "1.333rem",
      1: "1rem",
      "02": "0.75rem",
      "03": "0.563rem",
      "04": "0.317rem",
      "05": "0.238rem",
      "06": "0.178rem",
    },
    sizes: {
      content: "45rem",
      logo: "1.333rem",
    },
    space: {
      9: "9.969rem",
      8: "7.478rem",
      7: "5.61rem",
      6: "4.209rem",
      5: "3.157rem",
      4: "2.369rem",
      3: "1.777rem",
      2: "1.333rem",
      1: "1rem",
      "02": "0.75rem",
      "03": "0.563rem",
      "04": "0.317rem",
      "05": "0.238rem",
      "06": "0.178rem",
    },
    colors: {
      ...whiteA,
      ...grayA,
      ...mauveA,
      ...slateA,
      ...gray,
      ...mauve,
      ...slate,
      ...sage,
      ...olive,
      ...sand,
      ...tomato,
      ...red,
      ...crimson,
      ...pink,
      ...plum,
      ...purple,
      ...violet,
      ...indigo,
      ...blue,
      ...cyan,
      ...teal,
      ...green,
      ...grass,
      ...brown,
      ...orange,
      ...sky,
      ...mint,
      ...lime,
      ...yellow,
      ...amber,
      ...gold,
      ...bronze,
    },
    shadows: {
      slim: "rgba(0, 0, 0, 0.15) 0px 2px 8px",
      lifted: "rgba(0, 0, 0, 0.08) 0px 4px 12px",
    },
  },
});

export default styled;

/*
const darkTheme = createTheme({
  colors: {
    ...grayDark,
    ...blueDark,
    ...redDark,
    ...greenDark,
  },
});
*/
